name: Build exolvl

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Lua
        run: sudo apt-get install -y lua5.4

      - name: Generate exolvl
        run: lua generate.lua

      - name: Upload exolvl
        uses: actions/upload-artifact@v4
        with:
          name: level
          path: test.exolvl
